### PR TITLE
Feature/not in set - Add not in set operator

### PR DESCRIPTION
**Pull request by Glangouet**
Add 'not in set' operator to only enabled toggle if 'not in set' condition is true

### CODE REVIEW

**Comment by othillo** [comment]
duplicates #46

**Comment by wjzijderveld** [comment]
Fixed with #46 
Thanks for the PR though!

**Comment by othillo** [comment]
Thank you @Glangouet!

**Comment by Glangouet** [comment]
you're welcome :+1:

**Pull request closed without merging**
