### PR TITLE
Bumbed minimal PHP version + adjusted travis config in general

### PR DESCRIPTION
**Pull request by wjzijderveld**

### CODE REVIEW

**Comment by asm89** [comment]
:+1:

**Comment by othillo** [comment]
tnx, @wjzijderveld ;)

**Comment by bench1ps** [comment]
Hey guys ! Just a quick question: why was this required in the first place ? Because our prod servers are still on 5.4 and I can't update the lib :(

**Comment by wjzijderveld** [comment]
@bench1ps Mainly because PHP 5.4 support has ended over a year ago, and even security support has ended now. As I don't feel for keep support those old version and given we are still in 0.x versions, now was the time to do it.

I tagged 0.3.1 on the commit before this merge, so that is the latest version that allows 5.4
But I see that it's quit annoying that you now can't use the changes of your own PR now :disappointed:

**Comment by bench1ps** [comment]
So should I consider reporting the code of my PR ? :(

**Comment by wjzijderveld** [comment]
What do you mean?

**Comment by bench1ps** [comment]
Should I consider reporting my code related to multiple voting strategies on a branch deriving from the 0.3.1 tag so I can have access to the strategies AND not be limited by the platform requirements ? Does not sound like a good idea, I'm aware of that, but the only other way I can think of would be to ignore the platform requirements with composer, which we simply cannot afford on a production environment. Unless you reconsider and allow support for PHP 5.4 with maybe a suggestion ?

**Comment by wjzijderveld** [comment]
I would suggest to try and upgrade production :-)
Running your own fork is doable (I think you meant that?), but I can't
guarantee that we won't be using any 5.5+ features in the future, which
would make maintaining the fork a lot harder.

**Comment by bench1ps** [comment]
Un upgrade of the production is clearly an objective, but it won't be up and running too soon I'm afraid. Anyway, thanks for the tips, I'll run a custom fork for the moment.

**Pull request merged**
