### PR TITLE
Added InMemoryFactory to build Collections from array with examples

### PR DESCRIPTION
**Pull request by ricbra**
Hi @asm89

Instead of creating a YmlCollection I thought I would make more sense to delegate the creation of a collection based on an array to a <code>InMemoryCollectionFactory</code>. Users are free to create an array from whatever source (Yaml example supplied).

I'm open for feedback or improvements. Merging is also fine of course :).

### CODE REVIEW

**Comment by wjzijderveld** [comment]
Looks interesting, but I don't have the time at the moment to take a closer look.
I _hope_ create some time this evening..

**Comment by bench1ps** [comment]
Hi ! IMHO it doesn't make so much sense to have a factory which sole purpose is to create an `InMemoryCollection`, as it is pretty straightforward to actually create it. But I agree that the creation process should be a bit simpler, in order to set the whole collection at the same time from the outside. I would have simply implemented the constructor on the `InMemoryCollection` with an array as argument. Only an opinion though.

**Comment by ricbra** [comment]
I confess I also doubted a bit about the solution chosen. I also thought about placing all the deserialisation stuff in the constructor (or a static <code>createFromArray</code> method) , but it felt strange too pull in all those dependencies in an <code>InMemoryCollection</code>. One could argue it violates the SOLID principle.

But since it is just a simple <code>InMemoryCollection</code> maybe it doesn't matter at all. We all agree we need to have the deserialisation code somewhere. We only need a good place :).

**Comment by ricbra** [comment]
Could you shed some light on this PR too @wjzijderveld :smile:

**Comment by wjzijderveld** [comment]
Would it be an idea to add methods to the ToggleSerializer that allows to (de)serialize multiple toggles, and add a constructor to the InMemoryCollection that accepts an array with toggles?
That way we don't need to Factory that feels almost useless, but still have an easy way to deserialize a toggle collection.

**Comment by wjzijderveld** [comment]
I just played with this a bit more. And I can't find a good solution for this.
Main problem is deserializing any other collection then the InMemory collection is pretty hard. At least, not without adding a factory that would have knowledge about all the collections we might support in the future.

So I came to the conclusion that this PR is probably a good idea :smiley: 

But maybe we should look at it as a serializer instead of a factory. So maybe a `InMemoryCollectionSerializer`. For deserialization it would probably do the same thing as this Factory , but it's a bit more honest about what it actually does :smile: 

What do you think @ricbra? /cc @asm89

**Comment by ricbra** [comment]
This PR went a bit off my radar. After reading your comment and checking my PR again after quite some time I must agree <code>InMemoryCollectionSerializer</code> is a better name.

I'm ok by refactoring it into <code>InMemoryCollectionSerializer::serialize()</code> and <code>InMemoryCollectionSerializer::deserialize()</code>.

**Comment by ricbra** [comment]
Hi @wjzijderveld I've just updated the PR: refactored into <code>InMemoryCollectionSerializer</code>, added <code>serialize</code> and <code>deserialize</code>. Moved to <code>Serializer</code> namspace. Updated tests and example.

**Comment by wjzijderveld** [comment]
@ricbra Would you mind adding 1 test? A test that checks if deserializing a just serialized collection ends up with the same result you started with?

**Comment by ricbra** [comment]
I've updated the PR with a new test case. Also discovered a bug which I fixed (and also updated the example I created).

**Pull request merged**
